

if __name__ == '__main__':
    # try excepy 用来捕捉异常
    # a="1234567"
    # # try 用于异常处理,如果异常则执行except中的代码
    # try:
    #     # 判断a里面有没有9.
    #     assert '7' in a
    # except:
    #     print('a里面没有9')
    # # 不管是否有异常,finally里的代码都会执行
    # finally:
    #     print('最后-----')
    pass

